Add option to skip barrier marker events in traces
AMDResearch/omnitrace pull request #320
Opened 2023-12-14 22:04 UTC by tbennun

When inspecting traces with multiple queues, barrier events can be overwhelming on the profile. This PR creates a config entry to not include those in the output file. The configuration is disabled by default, so it should not affect the existing behavior.

2023-12-14 22:28 UTC, jrmadsen requested changes
Just requesting that "perfetto" is removed from the categories of the option because this isn't a setting that is perfetto-specific

2023-12-14 22:28 UTC, jrmadsen commented on source/lib/core/config.cpp
> +                             "roctracer", "rocm", "perfetto", "advanced");
```suggestion
                             "roctracer", "rocm", "advanced");
```

2023-12-14 23:57 UTC, tbennun commented
@jrmadsen Done, thank you.

2023-12-18 20:44 UTC, tbennun commented
@jrmadsen Reran clang-format, hopefully it all passes now.

2023-12-18 22:29 UTC, jrmadsen commented
> @jrmadsen Reran clang-format, hopefully it all passes now.

We’ve currently got a problem with the MPI test cases when they run on the free GitHub runners so it’s unlikely everything will pass. We are currently evaluating how we want to proceed

2024-01-10 13:17 UTC, merged